"""Add Conversation.phase and Sequence model

Revision ID: 2f7b63a7258d
Revises: 6c06fa6edab4
Create Date: 2025-04-25 17:16:39.329870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7b63a7258d'
down_revision = '6c06fa6edab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sequence_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sequences_conversation_id'), ['conversation_id'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase', sa.String(length=32), nullable=False, server_default="gathering"))
        batch_op.alter_column("phase", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('phase')

    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sequences_conversation_id'))

    op.drop_table('sequences')
    # ### end Alembic commands ###
