"""conversation title added

Revision ID: 34816f61a406
Revises: 713a6fd8301e
Create Date: 2025-05-13 18:36:33.959623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34816f61a406'
down_revision = '713a6fd8301e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
