"""added sequences and steps

Revision ID: 713a6fd8301e
Revises: 2f7b63a7258d
Create Date: 2025-04-26 12:43:38.521030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713a6fd8301e'
down_revision = '2f7b63a7258d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('step_text', sa.Text(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sequence_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sequence_steps_sequence_id'), ['sequence_id'], unique=False)

    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.drop_column('sequence_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_text', sa.TEXT(), autoincrement=False, nullable=False))

    with op.batch_alter_table('sequence_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sequence_steps_sequence_id'))

    op.drop_table('sequence_steps')
    # ### end Alembic commands ###
